name: Github to X(Proxies) PowerShell

on:
  workflow_dispatch:
    inputs:
      section:
        description: 'Which section to run? (kvms, apiproducts, developers, proxies, apps, keys, etc.)'
        required: true

env:

  DEPLOYMENT_NAME: Github to X(Proxies) # TODO: update to deployment name

 

  # Default Target Apigee Organization et environment (can be also be dynamically defined in [Set Variables *] steps)

  APIGEE_ORG: ${{ secrets.APIGEE_ORG }}

  APIGEE_ENV: ${{ secrets.APIGEE_ENV }}

  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  WORKFLOW_IDENTITY_FEDERATION_NAME: ${{ secrets.WORKFLOW_IDENTITY_FEDERATION_NAME }}

  APIGEE_BASE_URL: "https://apigee.googleapis.com/v1/organizations/"

 

jobs:

  apigee-window-artifacts:

    name: Proxies Export to Apigee X

    runs-on: ubuntu-latest

 

    permissions:

      contents: 'read'

      id-token: 'write'

 

    steps:

      - name: Check out repository code

        uses: actions/checkout@v3

        with:

          persist-credentials: false

          fetch-depth: 0

 

      # Configure Workload Identity Federation and generate an access token.

      - id: 'auth'

        name: 'Authenticate to Google Apigee Cloud'

        uses: 'google-github-actions/auth@v1'

        with:

          token_format: 'access_token'

          workload_identity_provider: 'projects/127369686749/locations/global/workloadIdentityPools/github-test/providers/github-test'

          service_account: 'workload-identity-federation@esi-apigee-x-394004.iam.gserviceaccount.com'


      - name: Downlod-File

        shell: pwsh

        run: |

          $env:ORG = "${{ secrets.APIGEE_ORG }}"

          $env:TOKEN = "${{ steps.auth.outputs.access_token }}"

          $env:GIT_TOKEN = "${{ secrets.TOKEN_GIT }}"

          Invoke-Pester ./scripts.ps1 -Passthru

 

      - name: Remove GCP Credentials JSON File

        run: rm gha-creds*.json
