name: Github to X(Proxies) PowerShell

on: push

 

env:

  DEPLOYMENT_NAME: Github to X(Proxies) # TODO: update to deployment name

 

  # Default Target Apigee Organization et environment (can be also be dynamically defined in [Set Variables *] steps)

  APIGEE_ORG: ${{ secrets.APIGEE_ORG }}

  APIGEE_ENV: ${{ secrets.APIGEE_ENV }}

  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  WORKFLOW_IDENTITY_FEDERATION_NAME: ${{ secrets.WORKFLOW_IDENTITY_FEDERATION_NAME }}

  APIGEE_BASE_URL: "https://apigee.googleapis.com/v1/organizations/"

 

jobs:

  apigee-window-artifacts:

    name: Artifacts Windows Export

    runs-on: windows-latest

 

    permissions:

      contents: 'read'

      id-token: 'write'

 

    steps:

      - name: Check out repository code

        uses: actions/checkout@v3

        with:

          persist-credentials: false

          fetch-depth: 0

 

      # Configure Workload Identity Federation and generate an access token.

      - id: 'auth'

        name: 'Authenticate to Google Apigee Cloud'

        uses: 'google-github-actions/auth@v1'

        with:

          token_format: 'access_token'

          workload_identity_provider: 'projects/127369686749/locations/global/workloadIdentityPools/github-test/providers/github-test'

          service_account: 'workload-identity-federation@esi-apigee-x-394004.iam.gserviceaccount.com'

      - name: Download Files
        run: |
          # PowerShell script to download files
          Invoke-Pester ./scripts.ps1 -Passthru
        env:
          git-token: ${{ secrets.TOKEN }}
          ORG: "${{ secrets.APIGEE_ORG }}"
          TOKEN: "${{ steps.auth.outputs.access_token }}"
        headers:
          Authorization: "Bearer ${{ secrets.TOKEN }}"
          "User-Agent": ".github/workflows/github-proxies-X.yml/1.0"


      - name: Perform Apigee Export

        shell: pwsh

        run: |

          $env:ORG = "${{ secrets.APIGEE_ORG }}"

          $env:TOKEN = "${{ steps.auth.outputs.access_token }}"

          Invoke-Pester ./scripts.ps1 -Passthru

 

      - name: Remove GCP Credentials JSON File

        run: rm gha-creds*.json
